[package]
name = "battery-friend"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive", "string"] }
dirs = "5.0.1"
notify = "6.1.1"
notify-rust = "4.11.0"
parse_duration = "2.1.1"
serde = { version = "1.0.204", features = ["derive"] }
toml = "0.8.14"
